<?php

namespace CarnetadressBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CarnetAdressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarnetAdressRepository extends EntityRepository
{
}
